name: CI workflow

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    
jobs:
  build: 
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          python --version  # Check Python version
          python -m pip install --upgrade pip

      - name: Install system dependencies
        run: |
          apt-get install -y sudo
          sudo apt-get update
          sudo apt-get install -y sqlite3 ca-certificates chromium-driver python3-selenium

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit test with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
